FROM node:14-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire server directory to the working directory
COPY server ./server

# Expose the port where the app will run
EXPOSE 5000

# Start the application
CMD ["node", "server/server.js"]
