name: EC2 Deploy

on:
  push:
    branches:
      - "*"
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.ref }}
          
      - name: Create SSH
        run: |
          bash -c 'mkdir -p ~/.ssh/ && echo "${{ secrets.MY_SECRET_SSH_KEY }}" > ~/.ssh/secretKey.pem && chmod 400 ~/.ssh/secretKey.pem'
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        run: |
          docker build -t mesgna/my-video-adder:latest ./server
          
      - name: Push Docker image to Docker Hub
        run: |
          docker push mesgna/my-video-adder:latest
          
      - name: Connect to EC2 and Run Container
        run: |
          ssh -i ~/.ssh/secretKey.pem -o StrictHostKeyChecking=no ubuntu@ec2-35-176-144-41.eu-west-2.compute.amazonaws.com <<'EOF'
            # Navigate to the project directory
           
  
            # Stop and remove existing container (handle potential errors)
            docker stop my-video-adder || true
            docker rm my-video-adder || true
  
            # Pull the latest Docker image
            docker pull mesgna/my-video-adder:latest
  
            # Run the new container with environment variables (consider secrets management)
            docker run -d -p 5000:5000 --name my-video-adder mesgna/my-video-adder:latest
          EOF
